name: Lwjgl3 Build
on:
  pull_request:
    branches-ignore:
      - ''
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 21
      - name: Build JRE JAR files
        run: |
          # Build JRE JAR files (security manager, etc...)
          gradle :jre_lwjgl3glfw:build --no-daemon --warning-mode all
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: lwjgl
          path: lwjgl3/*
